/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Staking__factory } from "./Staking__factory";
export { StakingToken__factory } from "./StakingToken__factory";
