/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyProxyAdmin__factory } from "./MyProxyAdmin__factory";
export { MyTransparentUpgradeableProxy__factory } from "./MyTransparentUpgradeableProxy__factory";
export { Staking__factory } from "./Staking__factory";
export { StakingToken__factory } from "./StakingToken__factory";
