/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MyProxyAdmin } from "./MyProxyAdmin";
export type { MyTransparentUpgradeableProxy } from "./MyTransparentUpgradeableProxy";
export type { Staking } from "./Staking";
export type { StakingToken } from "./StakingToken";
