/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eraTolenSol from "./EraTolen.sol";
export type { eraTolenSol };
import type * as airdropSol from "./airdrop.sol";
export type { airdropSol };
export type { MyProxyAdmin } from "./MyProxyAdmin";
export type { MyTransparentUpgradeableProxy } from "./MyTransparentUpgradeableProxy";
export type { Staking } from "./Staking";
export type { StakingToken } from "./StakingToken";
